"""
QUANTEX Position Manager — Full lifecycle management for trades.

Features:
- SL/TP monitoring with automatic execution
- Trailing stop logic (tightens as profit grows)
- Break-even trigger after first TP hit
- DCA entry ladder management
- Partial exit management for multi-level TPs
- Position risk scoring
"""
import time
import uuid
from dataclasses import dataclass, field
from typing import Optional


# ── Data Structures ──────────────────────────────────────

@dataclass
class TradePlan:
    """Complete trade plan generated by the strategy."""
    symbol: str
    direction: str
    entry_price: float
    quantity: float
    leverage: int
    confidence: float
    stop_loss: float
    take_profits: list[dict]  # [{level, price, qty_pct, trail, trail_dist}]
    slippage_bps: float = 0.3
    reason: str = ""
    regime: str = ""


@dataclass
class ManagedPosition:
    """Full position state with SL/TP management."""
    id: str
    symbol: str
    direction: str
    entry_price: float
    current_price: float
    quantity: float
    initial_quantity: float
    leverage: int
    stop_loss: float
    initial_stop_loss: float
    take_profits: list[dict]
    unrealized_pnl: float
    realized_pnl: float
    fees_paid: float
    status: str  # 'open', 'partially_closed', 'closed'
    break_even_triggered: bool
    opened_at: int
    closed_at: Optional[int] = None
    exit_reason: Optional[str] = None


# ── Position Manager ─────────────────────────────────────

class PositionManager:
    """
    Manages the full lifecycle of a trading position.
    
    Responsibilities:
    - Monitor SL/TP levels on each price update
    - Execute trailing stop logic
    - Trigger break-even stop after first TP
    - Execute partial exits for multi-level TPs
    - Track realized and unrealized PnL
    """

    def __init__(self):
        self._positions: dict[str, ManagedPosition] = {}

    def open_position(self, plan: TradePlan) -> ManagedPosition:
        """Open a new managed position from a trade plan."""
        # Build TP levels with tracking state
        tps = []
        for tp in plan.take_profits:
            tps.append({
                "level": tp.get("level", 1),
                "price": tp["price"],
                "qty_pct": tp.get("qty_pct", 0.5),
                "trail": tp.get("trail", False),
                "trail_dist": tp.get("trail_dist", None),
                "filled": False,
                "enabled": True,
            })

        position = ManagedPosition(
            id=str(uuid.uuid4()),
            symbol=plan.symbol,
            direction=plan.direction,
            entry_price=plan.entry_price,
            current_price=plan.entry_price,
            quantity=plan.quantity,
            initial_quantity=plan.quantity,
            leverage=plan.leverage,
            stop_loss=plan.stop_loss,
            initial_stop_loss=plan.stop_loss,
            take_profits=tps,
            unrealized_pnl=0.0,
            realized_pnl=0.0,
            fees_paid=0.0,
            status="open",
            break_even_triggered=False,
            opened_at=int(time.time() * 1000),
        )
        self._positions[position.id] = position
        return position

    def update_price(self, position_id: str, price: float) -> Optional[dict]:
        """
        Update position with the latest market price.
        Checks SL/TP levels and returns any exit actions needed.
        
        Returns:
            dict with action details if SL/TP hit, None otherwise
        """
        pos = self._positions.get(position_id)
        if not pos or pos.status == "closed":
            return None

        pos.current_price = price

        # Update unrealized PnL
        if pos.direction == "long":
            pos.unrealized_pnl = (price - pos.entry_price) * pos.quantity * pos.leverage
        else:
            pos.unrealized_pnl = (pos.entry_price - price) * pos.quantity * pos.leverage

        # Calculate profit percentage
        pnl_pct = (price - pos.entry_price) / pos.entry_price if pos.direction == "long" else \
                  (pos.entry_price - price) / pos.entry_price

        # ── Check Stop Loss ─────────────────
        if pos.direction == "long" and price <= pos.stop_loss:
            return self._close_position(pos, "sl")

        if pos.direction == "short" and price >= pos.stop_loss:
            return self._close_position(pos, "sl")

        # ── Check Take Profits ──────────────
        for tp in pos.take_profits:
            if tp["filled"] or not tp["enabled"]:
                continue

            hit = (pos.direction == "long" and price >= tp["price"]) or \
                  (pos.direction == "short" and price <= tp["price"])

            if hit:
                tp["filled"] = True
                qty_to_close = pos.quantity * tp["qty_pct"]

                # Calculate realized PnL for this partial exit
                if pos.direction == "long":
                    partial_pnl = (tp["price"] - pos.entry_price) * qty_to_close * pos.leverage
                else:
                    partial_pnl = (pos.entry_price - tp["price"]) * qty_to_close * pos.leverage

                pos.realized_pnl += partial_pnl
                pos.quantity -= qty_to_close

                tp_level = tp.get("level", 0)
                
                # ── Level 1 TP: Move SL to breakeven ──
                if tp_level == 1:
                    pos.break_even_triggered = True
                    new_sl = pos.entry_price * 1.001 if pos.direction == "long" else pos.entry_price * 0.999
                    pos.stop_loss = new_sl

                # ── Higher level TPs: Enable trailing ──
                if tp_level >= 2 and tp.get("trail", False):
                    pass  # Trail handled in trailing stop logic below

                # ── Check if position fully closed ──
                if pos.quantity <= 0.00001:
                    return self._close_position(pos, f"tp{tp_level}")

                return {
                    "action": "partial_close",
                    "position_id": pos.id,
                    "level": tp_level,
                    "price": tp["price"],
                    "qty_closed": qty_to_close,
                    "realized_pnl": partial_pnl,
                    "remaining_qty": pos.quantity,
                    "new_stop_loss": pos.stop_loss,
                }

        # ── Trailing Stop Logic ─────────────────
        if pnl_pct > 0.03:  # More than 3% profit
            pos = self._update_trailing_stop(pos, pnl_pct)

        return None

    def _update_trailing_stop(self, pos: ManagedPosition, pnl_pct: float) -> ManagedPosition:
        """Update trailing stop based on profit level."""
        trail_mult = 2.0
        
        # Tighten trail as profit grows
        if pnl_pct > 0.10:
            trail_mult = 1.2
        elif pnl_pct > 0.05:
            trail_mult = 1.5
        elif pnl_pct > 0.03:
            trail_mult = 1.8

        # Use ATR-like distance (1% of price as baseline)
        trail_distance = pos.current_price * 0.01 * trail_mult

        if pos.direction == "long":
            new_stop = pos.current_price - trail_distance
            if new_stop > pos.stop_loss:
                pos.stop_loss = new_stop
        else:
            new_stop = pos.current_price + trail_distance
            if new_stop < pos.stop_loss:
                pos.stop_loss = new_stop

        return pos

    def _close_position(self, pos: ManagedPosition, reason: str) -> dict:
        """Close a position and return closure details."""
        if pos.direction == "long":
            final_pnl = (pos.current_price - pos.entry_price) * pos.quantity * pos.leverage
        else:
            final_pnl = (pos.entry_price - pos.current_price) * pos.quantity * pos.leverage

        total_pnl = pos.realized_pnl + final_pnl

        pos.status = "closed"
        pos.closed_at = int(time.time() * 1000)
        pos.exit_reason = reason
        pos.realized_pnl = total_pnl

        return {
            "action": "close",
            "position_id": pos.id,
            "reason": reason,
            "entry_price": pos.entry_price,
            "exit_price": pos.current_price,
            "qty": pos.quantity,
            "realized_pnl": total_pnl,
            "unrealized_pnl": 0.0,
        }

    def close_position(self, position_id: str, reason: str = "manual") -> Optional[dict]:
        """Manually close a position."""
        pos = self._positions.get(position_id)
        if not pos or pos.status == "closed":
            return None
        return self._close_position(pos, reason)

    def get_position(self, position_id: str) -> Optional[ManagedPosition]:
        """Get position details."""
        return self._positions.get(position_id)

    def get_all_positions(self) -> list[ManagedPosition]:
        """Get all open positions."""
        return [p for p in self._positions.values() if p.status == "open"]

    def get_closed_positions(self) -> list[ManagedPosition]:
        """Get all closed positions."""
        return [p for p in self._positions.values() if p.status == "closed"]


# ── Entry Ladder Builder ─────────────────────────────────

def build_entry_ladder(
    entry_price: float,
    direction: str,
    total_size: float,
    atr: float,
    num_levels: int = 3,
) -> list[dict]:
    """
    Build a DCA entry ladder with intelligent spacing.
    First entry is smallest (test position), subsequent entries are larger.
    """
    weights = [0.20, 0.35, 0.45][:num_levels]
    total_w = sum(weights)
    weights = [w / total_w for w in weights]

    ladder = []
    for i in range(num_levels):
        spacing = atr * (0.3 + i * 0.5)
        if direction == "long":
            price = entry_price - spacing
        else:
            price = entry_price + spacing

        ladder.append({
            "level": i + 1,
            "price": round(price, 2),
            "qty": round(total_size * weights[i], 6),
            "type": "market" if i == 0 else "limit",
            "status": "filled" if i == 0 else "pending",
        })

    return ladder


# ── Dynamic Exit Builder ─────────────────────────────────

def build_exit_structure(
    entry_price: float,
    direction: str,
    atr: float,
    confidence: float,
) -> dict:
    """
    Build dynamic multi-level exit structure.
    TP distances scale with confidence.
    """
    multiplier = 1.0 + (confidence - 0.5) * 2  # 0.5 conf = 1.0x, 1.0 conf = 2.0x

    if direction == "long":
        tp1 = entry_price + atr * 1.5 * multiplier
        tp2 = entry_price + atr * 3.0 * multiplier
        tp3 = entry_price + atr * 5.0 * multiplier
        sl = entry_price - atr * 1.5
    else:
        tp1 = entry_price - atr * 1.5 * multiplier
        tp2 = entry_price - atr * 3.0 * multiplier
        tp3 = entry_price - atr * 5.0 * multiplier
        sl = entry_price + atr * 1.5

    return {
        "stop_loss": round(sl, 2),
        "take_profits": [
            {"level": 1, "price": round(tp1, 2), "qty_pct": 0.35, "trail": False, "trail_dist": None},
            {"level": 2, "price": round(tp2, 2), "qty_pct": 0.35, "trail": True, "trail_dist": round(atr * 0.5, 2)},
            {"level": 3, "price": round(tp3, 2), "qty_pct": 0.30, "trail": True, "trail_dist": round(atr * 0.5, 2)},
        ],
        "break_even_at": round(tp1, 2),
    }
