# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agents.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'agents.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x61gents.proto\x12\x10sentinelx.agents\"q\n\rSignalRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x0e\n\x06\x63loses\x18\x03 \x03(\x01\x12\r\n\x05highs\x18\x04 \x03(\x01\x12\x0c\n\x04lows\x18\x05 \x03(\x01\x12\x0f\n\x07volumes\x18\x06 \x03(\x01\"\xef\x01\n\x0f\x43ouncilDecision\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x12\n\nfinal_side\x18\x03 \x01(\t\x12\x12\n\nbull_score\x18\x04 \x01(\x01\x12\x12\n\nbear_score\x18\x05 \x01(\x01\x12\x17\n\x0f\x63onsensus_score\x18\x06 \x01(\x01\x12\x16\n\x0e\x63onfidence_pct\x18\x07 \x01(\x01\x12\x11\n\trationale\x18\x08 \x01(\t\x12\x17\n\x0freasoning_chain\x18\t \x01(\t\x12\x0f\n\x07\x62locked\x18\n \x01(\x08\x12\x0e\n\x06\x61tr_14\x18\x0b \x01(\x01\" \n\rHealthRequest\x12\x0f\n\x07service\x18\x01 \x01(\t\"2\n\x0eHealthResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x0f\n\x07version\x18\x02 \x01(\t2\xb2\x01\n\x0c\x41gentCouncil\x12P\n\nDeliberate\x12\x1f.sentinelx.agents.SignalRequest\x1a!.sentinelx.agents.CouncilDecision\x12P\n\x0bHealthCheck\x12\x1f.sentinelx.agents.HealthRequest\x1a .sentinelx.agents.HealthResponseB*Z(github.com/sentinelx/go/pkg/proto/agentsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agents_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z(github.com/sentinelx/go/pkg/proto/agents'
  _globals['_SIGNALREQUEST']._serialized_start=34
  _globals['_SIGNALREQUEST']._serialized_end=147
  _globals['_COUNCILDECISION']._serialized_start=150
  _globals['_COUNCILDECISION']._serialized_end=389
  _globals['_HEALTHREQUEST']._serialized_start=391
  _globals['_HEALTHREQUEST']._serialized_end=423
  _globals['_HEALTHRESPONSE']._serialized_start=425
  _globals['_HEALTHRESPONSE']._serialized_end=475
  _globals['_AGENTCOUNCIL']._serialized_start=478
  _globals['_AGENTCOUNCIL']._serialized_end=656
# @@protoc_insertion_point(module_scope)
