# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from core.proto import agents_pb2 as agents__pb2



class AgentCouncilStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Deliberate = channel.unary_unary(
                '/sentinelx.agents.AgentCouncil/Deliberate',
                request_serializer=agents__pb2.SignalRequest.SerializeToString,
                response_deserializer=agents__pb2.CouncilDecision.FromString,
                _registered_method=False)
        self.HealthCheck = channel.unary_unary(
                '/sentinelx.agents.AgentCouncil/HealthCheck',
                request_serializer=agents__pb2.HealthRequest.SerializeToString,
                response_deserializer=agents__pb2.HealthResponse.FromString,
                _registered_method=False)


class AgentCouncilServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Deliberate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentCouncilServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Deliberate': grpc.unary_unary_rpc_method_handler(
                    servicer.Deliberate,
                    request_deserializer=agents__pb2.SignalRequest.FromString,
                    response_serializer=agents__pb2.CouncilDecision.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=agents__pb2.HealthRequest.FromString,
                    response_serializer=agents__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sentinelx.agents.AgentCouncil', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AgentCouncil(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Deliberate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentinelx.agents.AgentCouncil/Deliberate',
            agents__pb2.SignalRequest.SerializeToString,
            agents__pb2.CouncilDecision.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=False)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentinelx.agents.AgentCouncil/HealthCheck',
            agents__pb2.HealthRequest.SerializeToString,
            agents__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=False)
