# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from core.proto import risk_pb2 as risk__pb2



class RiskEngineStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Validate = channel.unary_unary(
                '/sentinelx.risk.RiskEngine/Validate',
                request_serializer=risk__pb2.RiskRequest.SerializeToString,
                response_deserializer=risk__pb2.RiskResponse.FromString,
                _registered_method=False)
        self.GetPortfolioHeat = channel.stream_stream(
                '/sentinelx.risk.RiskEngine/GetPortfolioHeat',
                request_serializer=risk__pb2.RiskRequest.SerializeToString,
                response_deserializer=risk__pb2.RiskResponse.FromString,
                _registered_method=False)
        self.SubscribeKillSwitch = channel.unary_stream(
                '/sentinelx.risk.RiskEngine/SubscribeKillSwitch',
                request_serializer=risk__pb2.KillSwitchRequest.SerializeToString,
                response_deserializer=risk__pb2.KillSwitchEvent.FromString,
                _registered_method=False)


class RiskEngineServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Validate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPortfolioHeat(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeKillSwitch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RiskEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Validate': grpc.unary_unary_rpc_method_handler(
                    servicer.Validate,
                    request_deserializer=risk__pb2.RiskRequest.FromString,
                    response_serializer=risk__pb2.RiskResponse.SerializeToString,
            ),
            'GetPortfolioHeat': grpc.stream_stream_rpc_method_handler(
                    servicer.GetPortfolioHeat,
                    request_deserializer=risk__pb2.RiskRequest.FromString,
                    response_serializer=risk__pb2.RiskResponse.SerializeToString,
            ),
            'SubscribeKillSwitch': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeKillSwitch,
                    request_deserializer=risk__pb2.KillSwitchRequest.FromString,
                    response_serializer=risk__pb2.KillSwitchEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sentinelx.risk.RiskEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RiskEngine(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Validate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentinelx.risk.RiskEngine/Validate',
            risk__pb2.RiskRequest.SerializeToString,
            risk__pb2.RiskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=False)

    @staticmethod
    def GetPortfolioHeat(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/sentinelx.risk.RiskEngine/GetPortfolioHeat',
            risk__pb2.RiskRequest.SerializeToString,
            risk__pb2.RiskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=False)

    @staticmethod
    def SubscribeKillSwitch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sentinelx.risk.RiskEngine/SubscribeKillSwitch',
            risk__pb2.KillSwitchRequest.SerializeToString,
            risk__pb2.KillSwitchEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=False)
