"""
Offline Nightly Training Loop — cron job for daily RL improvement.

Runs every night (e.g., 02:00 UTC):
1. Pulls all trades from Postgres (last 24h or configurable window)
2. Replays through backtest engine with simulated RL updates
3. Computes aggregate rewards and identifies patterns
4. Generates policy update prompt for LLM
5. Updates strategy rules / agent prompts
6. Logs metrics and saves policy version
"""

from __future__ import annotations

import json
import logging
import os
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any

import sys
sys.path.append(r"C:\Users\Mns Mns\OneDrive\Documents\GitHub\Trade_agent")

from orchestrator.rl_memory.memory_store import (
    TradeOutcome,
    RLMemoryManager,
    create_memory_manager,
)
from orchestrator.rl_memory.reward_function import (
    compute_reward,
    RewardConfig,
    get_reward_stats,
    generate_policy_update_prompt,
)

logger = logging.getLogger(__name__)


# ── Configuration ───────────────────────────────────────────────


@dataclass
class NightlyConfig:
    """Configuration for nightly training loop."""

    # Data window
    lookback_days: int = 1           # How many days of trades to process
    min_trades_for_update: int = 10  # Minimum trades needed to generate policy update

    # Paths
    policy_output_dir: str = "policies"  # Where to save updated policy files
    log_dir: str = "logs/nightly"        # Log directory

    # LLM settings for policy generation
    llm_provider: str = "ollama"         # ollama, openrouter, etc.
    llm_model: str = "qwen2.5:3b"        # Model for policy generation
    llm_base_url: str = "http://localhost:11434/v1"

    # Retention
    max_policy_versions: int = 30        # Keep last N policy versions

    @classmethod
    def from_env(cls) -> "NightlyConfig":
        return cls(
            lookback_days=int(os.getenv("NIGHTLY_LOOKBACK_DAYS", "1")),
            min_trades_for_update=int(os.getenv("NIGHTLY_MIN_TRADES", "10")),
            policy_output_dir=os.getenv("NIGHTLY_POLICY_DIR", "policies"),
            log_dir=os.getenv("NIGHTLY_LOG_DIR", "logs/nightly"),
            llm_provider=os.getenv("NIGHTLY_LLM_PROVIDER", "ollama"),
            llm_model=os.getenv("NIGHTLY_LLM_MODEL", "qwen2.5:3b"),
            llm_base_url=os.getenv("NIGHTLY_LLM_BASE_URL", "http://localhost:11434/v1"),
            max_policy_versions=int(os.getenv("NIGHTLY_MAX_VERSIONS", "30")),
        )


# ── Data Classes ────────────────────────────────────────────────


@dataclass
class NightlyReport:
    """Report generated by nightly loop."""

    run_id: str
    timestamp: datetime
    lookback_days: int
    trades_analyzed: int
    wins: int
    losses: int
    win_rate: float
    avg_reward: float
    total_pnl_pct: float
    sharpe: float
    policy_updated: bool
    policy_version: str | None
    policy_path: str | None
    errors: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "run_id": self.run_id,
            "timestamp": self.timestamp.isoformat(),
            "lookback_days": self.lookback_days,
            "trades_analyzed": self.trades_analyzed,
            "wins": self.wins,
            "losses": self.losses,
            "win_rate": self.win_rate,
            "avg_reward": self.avg_reward,
            "total_pnl_pct": self.total_pnl_pct,
            "sharpe": self.sharpe,
            "policy_updated": self.policy_updated,
            "policy_version": self.policy_version,
            "policy_path": self.policy_path,
            "errors": self.errors,
        }


# ── Nightly Loop Core ───────────────────────────────────────────


class NightlyTrainer:
    """Orchestrates the nightly RL improvement loop."""

    def __init__(self, config: NightlyConfig | None = None):
        self.config = config or NightlyConfig.from_env()
        self.memory_manager = create_memory_manager()
        self.reward_config = RewardConfig()

        # Setup paths
        self.policy_dir = Path(self.config.policy_output_dir)
        self.policy_dir.mkdir(parents=True, exist_ok=True)
        self.log_dir = Path(self.config.log_dir)
        self.log_dir.mkdir(parents=True, exist_ok=True)

        # Setup logging
        self._setup_logging()

    def _setup_logging(self):
        log_file = self.log_dir / f"nightly_{datetime.now().strftime('%Y%m%d')}.log"
        handler = logging.FileHandler(log_file)
        handler.setFormatter(logging.Formatter(
            "%(asctime)s | %(levelname)-8s | %(message)s"
        ))
        logger.addHandler(handler)
        logger.setLevel(logging.INFO)

    def run(self) -> NightlyReport:
        """Execute the full nightly training loop."""
        run_id = str(uuid.uuid4())[:8]
        timestamp = datetime.now()
        errors = []

        logger.info(f"=== Nightly Training Loop Started (run_id={run_id}) ===")

        try:
            # 1. Fetch trades from Postgres
            trades = self._fetch_trades()
            logger.info(f"Fetched {len(trades)} trades from last {self.config.lookback_days} day(s)")

            if len(trades) < self.config.min_trades_for_update:
                msg = f"Insufficient trades ({len(trades)} < {self.config.min_trades_for_update}), skipping policy update"
                logger.warning(msg)
                return NightlyReport(
                    run_id=run_id,
                    timestamp=timestamp,
                    lookback_days=self.config.lookback_days,
                    trades_analyzed=len(trades),
                    wins=0,
                    losses=0,
                    win_rate=0.0,
                    avg_reward=0.0,
                    total_pnl_pct=0.0,
                    sharpe=0.0,
                    policy_updated=False,
                    policy_version=None,
                    policy_path=None,
                    errors=[msg],
                )

            # 2. Compute rewards for all trades
            rewards, breakdowns = zip(*[compute_reward(t, self.reward_config) for t in trades])

            # 3. Split wins/losses
            winning_trades = [t for t, r in zip(trades, rewards) if r > 0]
            losing_trades = [t for t, r in zip(trades, rewards) if r <= 0]

            # 4. Compute aggregate stats
            stats = get_reward_stats(trades, self.reward_config)

            # 5. Generate policy update prompt
            policy_prompt = generate_policy_update_prompt(
                winning_trades, losing_trades, self.reward_config
            )

            # 6. Call LLM to generate improved policy
            policy_json = self._call_llm_for_policy(policy_prompt)
            if not policy_json:
                errors.append("LLM policy generation failed")
                policy_updated = False
                policy_version = None
                policy_path = None
            else:
                # 7. Save policy version
                policy_version, policy_path = self._save_policy(policy_json, timestamp)
                policy_updated = True

            # 6. Log report
            report = NightlyReport(
                run_id=run_id,
                timestamp=timestamp,
                lookback_days=self.config.lookback_days,
                trades_analyzed=len(trades),
                wins=len(winning_trades),
                losses=len(losing_trades),
                win_rate=len(winning_trades) / len(trades),
                avg_reward=stats.get("mean", 0.0),
                total_pnl_pct=sum(t.pnl_pct for t in trades) * 100,
                sharpe=stats.get("sharpe", 0.0),
                policy_updated=policy_updated,
                policy_version=policy_version,
                policy_path=policy_path,
                errors=errors,
            )

            self._save_report(report)
            logger.info(f"=== Nightly Training Loop Completed ===")
            logger.info(f"  Trades: {len(trades)} | Win Rate: {report.win_rate:.2%} | Sharpe: {report.sharpe:.3f}")
            logger.info(f"  Policy Updated: {policy_updated} | Version: {policy_version}")

            return report

        except Exception as e:
            logger.exception(f"Nightly loop failed: {e}")
            errors.append(str(e))
            return NightlyReport(
                run_id=run_id,
                timestamp=timestamp,
                lookback_days=self.config.lookback_days,
                trades_analyzed=0,
                wins=0,
                losses=0,
                win_rate=0.0,
                avg_reward=0.0,
                total_pnl_pct=0.0,
                sharpe=0.0,
                policy_updated=False,
                policy_version=None,
                policy_path=None,
                errors=errors,
            )

    def _fetch_trades(self) -> list[TradeOutcome]:
        """Fetch trades from Postgres (long-term memory)."""
        if not self.memory_manager.is_available("postgres"):
            logger.warning("Postgres not available, using Redis fallback")
            if self.memory_manager.is_available("redis"):
                return self.memory_manager.get_recent_trades(1000)
            return []

        end = datetime.now()
        start = end - timedelta(days=self.config.lookback_days)
        return self.memory_manager.postgres.get_trades(start=start, end=end, limit=10000)

    def _call_llm_for_policy(self, prompt: str) -> dict | None:
        """Call LLM to generate improved policy rules."""
        try:
            import openai
            client = openai.OpenAI(
                base_url=self.config.llm_base_url,
                api_key="ollama",  # Ollama uses dummy key
            )
            response = client.chat.completions.create(
                model=self.config.llm_model,
                messages=[
                    {"role": "system", "content": "You are a trading strategy optimizer. Output only valid JSON."},
                    {"role": "user", "content": prompt},
                ],
                temperature=0.3,
                max_tokens=2000,
            )
            content = response.choices[0].message.content
            return json.loads(content)
        except Exception as e:
            logger.error(f"LLM call failed: {e}")
            return None

    def _save_policy(self, policy_json: dict, timestamp: datetime) -> tuple[str, str]:
        """Save policy version to disk."""
        version = f"v{timestamp.strftime('%Y%m%d_%H%M%S')}"
        policy_json["version"] = version
        policy_json["created_at"] = timestamp.isoformat()
        policy_json["source"] = "nightly_rl_loop"

        # Save new version
        path = self.policy_dir / f"policy_{version}.json"
        with open(path, "w") as f:
            json.dump(policy_json, f, indent=2)

        # Cleanup old versions
        self._cleanup_old_policies()

        logger.info(f"Saved policy version {version} to {path}")
        return version, str(path)

    def _cleanup_old_policies(self):
        """Keep only the most recent N policy versions."""
        policies = sorted(self.policy_dir.glob("policy_v*.json"))
        if len(policies) > self.config.max_policy_versions:
            for old in policies[:-self.config.max_policy_versions]:
                old.unlink()
                logger.debug(f"Removed old policy: {old.name}")

    def _save_report(self, report: NightlyReport):
        """Save nightly report to JSON."""
        path = self.log_dir / f"report_{report.run_id}.json"
        with open(path, "w") as f:
            json.dump(report.to_dict(), f, indent=2)


# ── CLI Entry Point ─────────────────────────────────────────────


def main():
    """CLI entry point for cron job."""
    import argparse

    parser = argparse.ArgumentParser(description="Nightly RL Training Loop")
    parser.add_argument("--lookback", type=int, default=1, help="Days of trades to analyze")
    parser.add_argument("--min-trades", type=int, default=10, help="Minimum trades for policy update")
    parser.add_argument("--policy-dir", default="policies", help="Policy output directory")
    parser.add_argument("--log-dir", default="logs/nightly", help="Log directory")
    parser.add_argument("--llm-model", default="qwen2.5:3b", help="LLM model for policy generation")
    parser.add_argument("--llm-url", default="http://localhost:11434/v1", help="LLM base URL")
    parser.add_argument("--dry-run", action="store_true", help="Run without saving policy")

    args = parser.parse_args()

    config = NightlyConfig(
        lookback_days=args.lookback,
        min_trades_for_update=args.min_trades,
        policy_output_dir=args.policy_dir,
        log_dir=args.log_dir,
        llm_model=args.llm_model,
        llm_base_url=args.llm_url,
    )

    trainer = NightlyTrainer(config)
    report = trainer.run()

    # Exit code: 0 = success, 1 = error, 2 = skipped (insufficient trades)
    if report.errors:
        exit(1)
    elif not report.policy_updated and report.trades_analyzed < args.min_trades:
        exit(2)
    else:
        exit(0)


if __name__ == "__main__":
    main()